package com.enoch.chris.lessonplanwebsite.config;

import javax.servlet.http.HttpServletRequest;

import java.util.Enumeration;

import javax.servlet.RequestDispatcher;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.web.error.ErrorAttributeOptions;
import org.springframework.boot.web.servlet.error.ErrorAttributes;
import org.springframework.boot.web.servlet.error.ErrorController;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.context.request.RequestAttributes;
import org.springframework.web.context.request.ServletRequestAttributes;

/**
 * This replaces the whitelabel error page automatically generated by Spring.
 * @author chris
 *
 */
@Controller
public class ErrorConfiguration implements ErrorController  {
	
	  @Autowired
	  private ErrorAttributes errorAttributes;

    @RequestMapping("/error")
    public String handleError(HttpServletRequest request) {  	

        return "error";
    }
    
//    @RequestMapping("/showerror")
//    public String handleError() {
//    
//    	System.out.println("debugging - inside show Error - ErrorConfiguration");
//
//        return "error";
//    }
}
